name: covid19stat
description: A new Flutter project.

version: 0.0.3+1
environment:
  sdk: ">=2.3.5 <3.0.0"

dependencies:
  matrix_gesture_detector: ^0.1.0
  animated_card: ^1.0.0+8
  draggable_scrollbar: ^0.0.4
  firebase_database: ^3.1.5
  intl: ^0.16.1
  package_info: ^0.4.0+16
  expandable: ^3.0.0
  get_it: ^4.0.1
  firebase_messaging: ^6.0.13
  font_awesome_flutter: ^8.8.1
  solid_bottom_sheet: ^0.1.9
  cloud_firestore:
  url_launcher: ^5.4.2
  jiffy: ^3.0.1
  auto_size_text: ^2.1.0
  dropdown_formfield: ^0.1.1
  animate_do: ^1.6.3
  provider: ^4.1.2
  share: ^0.6.4+2
  autocomplete_textfield: ^1.7.3
  shared_preferences: ^0.5.6+3
  table_sticky_headers: ^1.1.2
  liquid_pull_to_refresh: ^2.0.0
  http:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.3+1
  built_path: ^0.1.0
  built_path_annotations: ^0.1.0
  charts_flutter: ^0.9.0
  path_drawing: ^0.4.1
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4

dependency_overrides:
  analyzer: ^0.39.4
  build: ^1.2.2

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/in.svg
    - assets/launcher/icon.png
    - assets/launcher/19.png
  #  - maps/india.json
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg


  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/archia-regular-webfont.ttf